[2022-01-31 15:52:45,531] {taskinstance.py:670} INFO - Dependencies all met for <TaskInstance: twitter_dag.twitter_aluraonline 2022-01-29T09:00:00+00:00 [queued]>
[2022-01-31 15:52:45,535] {taskinstance.py:670} INFO - Dependencies all met for <TaskInstance: twitter_dag.twitter_aluraonline 2022-01-29T09:00:00+00:00 [queued]>
[2022-01-31 15:52:45,535] {taskinstance.py:880} INFO - 
--------------------------------------------------------------------------------
[2022-01-31 15:52:45,536] {taskinstance.py:881} INFO - Starting attempt 1 of 1
[2022-01-31 15:52:45,536] {taskinstance.py:882} INFO - 
--------------------------------------------------------------------------------
[2022-01-31 15:52:45,541] {taskinstance.py:901} INFO - Executing <Task(TwitterOperator): twitter_aluraonline> on 2022-01-29T09:00:00+00:00
[2022-01-31 15:52:45,543] {standard_task_runner.py:54} INFO - Started process 16299 to run task
[2022-01-31 15:52:45,572] {standard_task_runner.py:77} INFO - Running: ['airflow', 'run', 'twitter_dag', 'twitter_aluraonline', '2022-01-29T09:00:00+00:00', '--job_id', '19', '--pool', 'default_pool', '--raw', '-sd', 'DAGS_FOLDER/twitter_dag.py', '--cfg_path', '/tmp/tmp3p3xd1nb']
[2022-01-31 15:52:45,572] {standard_task_runner.py:78} INFO - Job 19: Subtask twitter_aluraonline
[2022-01-31 15:52:45,586] {logging_mixin.py:112} INFO - Running <TaskInstance: twitter_dag.twitter_aluraonline 2022-01-29T09:00:00+00:00 [running]> on host 1a222f561522
[2022-01-31 15:52:45,618] {base_hook.py:89} INFO - Using connection to: id: twitter_default. Host: https://api.twitter.com, Port: None, Schema: None, Login: None, Password: None, extra: XXXXXXXX
[2022-01-31 15:52:45,619] {twitter_hook.py:36} INFO - URL: https://api.twitter.com/2/tweets/search/recent?query=AluraOnline&tweet.fields=author_id,conversation_id,created_at,id,in_reply_to_user_id,public_metrics,text&expansions=author_id&user.fields=id,name,username,created_at&start_time=2022-01-29T09:00:00.00Z&end_time=2022-01-30T09:00:00.00Z
[2022-01-31 15:52:45,639] {logging_mixin.py:112} WARNING - /run/datapipeline/.env/lib/python3.8/site-packages/urllib3/connectionpool.py:981: InsecureRequestWarning: Unverified HTTPS request is being made to host 'api.twitter.com'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
  warnings.warn(
[2022-01-31 15:52:45,924] {twitter_hook.py:36} INFO - URL: https://api.twitter.com/2/tweets/search/recent?query=AluraOnline&tweet.fields=author_id,conversation_id,created_at,id,in_reply_to_user_id,public_metrics,text&expansions=author_id&user.fields=id,name,username,created_at&start_time=2022-01-29T09:00:00.00Z&end_time=2022-01-30T09:00:00.00Z&next_token=b26v89c19zqg8o3fpe482by2mxnbz8dpqw7pxjisa7725
[2022-01-31 15:52:45,924] {logging_mixin.py:112} WARNING - /run/datapipeline/.env/lib/python3.8/site-packages/urllib3/connectionpool.py:981: InsecureRequestWarning: Unverified HTTPS request is being made to host 'api.twitter.com'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
  warnings.warn(
[2022-01-31 15:52:46,210] {twitter_hook.py:36} INFO - URL: https://api.twitter.com/2/tweets/search/recent?query=AluraOnline&tweet.fields=author_id,conversation_id,created_at,id,in_reply_to_user_id,public_metrics,text&expansions=author_id&user.fields=id,name,username,created_at&start_time=2022-01-29T09:00:00.00Z&end_time=2022-01-30T09:00:00.00Z&next_token=b26v89c19zqg8o3fpe482bx5z0ybbfbfygogyu2g66f7h
[2022-01-31 15:52:46,210] {logging_mixin.py:112} WARNING - /run/datapipeline/.env/lib/python3.8/site-packages/urllib3/connectionpool.py:981: InsecureRequestWarning: Unverified HTTPS request is being made to host 'api.twitter.com'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
  warnings.warn(
[2022-01-31 15:52:46,481] {twitter_hook.py:36} INFO - URL: https://api.twitter.com/2/tweets/search/recent?query=AluraOnline&tweet.fields=author_id,conversation_id,created_at,id,in_reply_to_user_id,public_metrics,text&expansions=author_id&user.fields=id,name,username,created_at&start_time=2022-01-29T09:00:00.00Z&end_time=2022-01-30T09:00:00.00Z&next_token=b26v89c19zqg8o3fpe4829tcg2mvif567x5j88bmezywt
[2022-01-31 15:52:46,481] {logging_mixin.py:112} WARNING - /run/datapipeline/.env/lib/python3.8/site-packages/urllib3/connectionpool.py:981: InsecureRequestWarning: Unverified HTTPS request is being made to host 'api.twitter.com'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
  warnings.warn(
[2022-01-31 15:52:46,702] {taskinstance.py:1057} INFO - Marking task as SUCCESS.dag_id=twitter_dag, task_id=twitter_aluraonline, execution_date=20220129T090000, start_date=20220131T155245, end_date=20220131T155246
[2022-01-31 15:52:50,527] {local_task_job.py:102} INFO - Task exited with return code 0
